version: "3.7"

x-default-opts: &default-opts
  logging:
    options:
      max-size: "1m"
  # driver: "gelf"
  # options:
  #   gelf-address: "udp://127.0.0.1:5000"

services:
  web:
    <<: *default-opts
    image: portainer/portainer
    # command: -H "tcp://tasks.agent:9001"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      # place on managers when not using agent, place on workers if using agent
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
        - "traefik.http.routers.portainer.rule=Path(`/portainer`)"
        - "traefik.http.routers.portainer.entrypoints=web-secured"
        - "traefik.http.routers.portainer.tls.certresolver=mytlschallenge"
    networks:
      - traefik-public
      - portainer
    volumes:
      - web:/data
  # agent:
  #   <<: *default-opts
  #   image: portainer/agent
  #   networks:
  #     - portainer
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   deploy:
  #     mode: global
  #   environment:
  #     AGENT_CLUSTER_ADDR: tasks.agent

networks:
  traefik-public:
    external: true
  portainer:

volumes:
  web:
    # driver: rexray/dobs
    # driver_opts:
    #   size: 1
